{
 "title": "Synapse - K8s 集群总览",
 "tags": [
  "kubernetes",
  "cluster",
  "synapse"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "数据源", "query": "prometheus" },
   { "name": "cluster", "label": "集群", "query": { "query": "label_values(up, cluster)" } },
   { "name": "zone", "label": "可用区", "query": "sh1,sh2" }
  ]
 },
 "panels": [
  { "title": "资源池", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  { "type": "text", "gridPos": { "x": 0, "y": 1, "w": 3, "h": 2 }, "options": { "content": "\n## ${cluster}-${zone}" } },
  {
   "title": "工作节点数",
   "type": "stat",
   "gridPos": { "x": 3, "y": 1, "w": 3, "h": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})"
    }
   ]
  },
  {
   "title": "CPU 总核数",
   "type": "stat",
   "gridPos": { "x": 6, "y": 1, "w": 3, "h": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{cluster=~\"$cluster\"} * on(node) group_left() (kube_node_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}))"
    }
   ]
  },
  {
   "title": "内存总数",
   "type": "stat",
   "gridPos": { "x": 9, "y": 1, "w": 3, "h": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{cluster=~\"$cluster\"} * on(node) group_left() (kube_node_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}))"
    }
   ]
  },
  {
   "title": "Pod 最大可创建数",
   "type": "stat",
   "gridPos": { "x": 12, "y": 1, "w": 3, "h": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource='pods',cluster=~\"$cluster\"} * on(node) group_left() (kube_node_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}))"
    }
   ]
  },
  {
   "title": "Pod 已创建数",
   "type": "stat",
   "gridPos": { "x": 15, "y": 1, "w": 3, "h": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})"
    }
   ]
  },
  {
   "title": "Pod 使用率",
   "type": "stat",
   "gridPos": { "x": 18, "y": 1, "w": 3, "h": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\"}) / sum(kube_node_status_capacity{resource='pods',cluster=~\"$cluster\"} * on(node) group_left() (kube_node_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}))",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "Pod 可创建数",
   "type": "stat",
   "gridPos": { "x": 21, "y": 1, "w": 3, "h": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource='pods',cluster=~\"$cluster\"} * on(node) group_left() (kube_node_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})) - sum(kube_pod_info{cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})"
    }
   ]
  },
  { "title": "集群状态", "type": "row", "gridPos": { "x": 0, "y": 3, "w": 24, "h": 1 } },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 2, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "apiserver 近30天可用率",
   "type": "stat",
   "gridPos": { "x": 14, "y": 4, "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\",cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "CPU request",
   "type": "stat",
   "gridPos": { "x": 16, "y": 4, "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}) / sum(kube_node_status_allocatable{resource=\"cpu\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})"
    }
   ]
  },
  {
   "title": "CPU limit",
   "type": "stat",
   "gridPos": { "x": 18, "y": 4, "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}) / sum(kube_node_status_allocatable{resource=\"cpu\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})"
    }
   ]
  },
  {
   "title": "内存 request",
   "type": "stat",
   "gridPos": { "x": 20, "y": 4, "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}) / sum(kube_node_status_allocatable{resource=\"memory\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})"
    }
   ]
  },
  {
   "title": "内存 limit",
   "type": "stat",
   "gridPos": { "x": 22, "y": 4, "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'}) / sum(kube_node_status_allocatable{resource=\"memory\",cluster=~\"$cluster\"} unless on(node) kube_node_role{cluster=~\"$cluster\",role='control-plane'})"
    }
   ]
  },
  {
   "title": "apiserver总请求量",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "总请求量"
    }
   ]
  },
  {
   "title": "集群 CPU 使用率",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\"}[$__rate_interval]) unless on(instance) label_replace(kube_node_info * on(node) group_left() kube_node_role{role=\"control-plane\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.+)\"))",
     "legendFormat": "CPU 使用率"
    }
   ]
  },
  {
   "title": "集群内存使用率",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes{cluster=~\"$cluster\"} unless on(instance) label_replace(kube_node_info * on(node) group_left() kube_node_role{role=\"control-plane\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.+)\")) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"} unless on(instance) label_replace(kube_node_info * on(node) group_left() kube_node_role{role=\"control-plane\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.+)\"))",
     "legendFormat": "内存使用率"
    }
   ]
  },
  { "title": "Node 资源使用", "type": "row", "gridPos": { "x": 0, "y": 12, "w": 24, "h": 1 } },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 13, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\"}[$__rate_interval]) unless on(instance) label_replace(kube_node_info * on(node) group_left() kube_node_role{role=\"control-plane\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.+)\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 13, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{cluster=~\"$cluster\"} / node_memory_MemTotal_bytes{cluster=~\"$cluster\"} unless on(instance) label_replace(kube_node_info * on(node) group_left() kube_node_role{role=\"control-plane\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.+)\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load 饱和度",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{cluster=~\"$cluster\"} / on(instance) group_left count by(instance) (node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\"} unless on(instance) label_replace(kube_node_info * on(node) group_left() kube_node_role{role=\"control-plane\"}, \"instance\", \"$1:9100\", \"internal_ip\", \"(.+)\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network Traffic",
   "gridPos": { "x": 12, "y": 20, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth0|bond0|ens.*\",cluster=~\"$cluster\"}[5m]) * 8",
     "legendFormat": "recv {{instance}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth0|bond0|ens.*\",cluster=~\"$cluster\"}[5m]) * 8",
     "legendFormat": "trans {{instance}}"
    }
   ]
  },
  { "title": "Pod 情况", "type": "row", "gridPos": { "x": 0, "y": 27, "w": 24, "h": 1 } },
  {
   "title": "Pod 异常列表",
   "type": "table",
   "gridPos": { "x": 0, "y": 28, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{condition=\"false\",cluster=~\"$cluster\"} == 1"
    }
   ]
  },
  {
   "title": "异常 Pod 分布情况",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 28, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(namespace) (kube_pod_status_ready{condition=\"false\",cluster=~\"$cluster\"} == 1)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}