apiVersion: v2
name: synapse
description: Enterprise-Grade Kubernetes Multi-Cluster Management Platform
type: application
version: 1.0.5
appVersion: "1.0.5"

keywords:
  - kubernetes
  - management
  - multi-cluster
  - devops
  - k8s

home: https://synapse.clay-wangzhi.com
sources:
  - https://github.com/clay-wangzhi/Synapse

maintainers:
  - name: Synapse Team
    email: support@synapse.io
    url: https://github.com/clay-wangzhi

icon: https://synapse.clay-wangzhi.com/img/logo.svg

annotations:
  category: Infrastructure
  licenses: Apache-2.0
